### ISSUE TITLE
missing vertices and books

### ISSUE THREAD

**Issue by Assafcohen1989** [TechnionTDK/jbs-web-tagger#29]
Hi all,
In the current version of the web tagger v0.1 I noticed the following problems:
1.  is no separation between Divrey Hayamin A and B and nor for Shmuel A and B and nor for Melachim A and B.
2. In book Dvarim Chapter 13 there are only 10 vertices instead of 18.

@omishali  @TechnionTDK/team-jbs-web-tagger

**Comment by omishali** [comment]
Hi Assaf, they rely on the same jbs-text files that you use and that
contain errors. I hope that in the next week we will have a fixed version.

בתאריך 5 בינו׳ 2017 6:23 אחה״צ,‏ "Assaf Cohen" <notifications@github.com>
כתב:

Hi all,
In the current version of the web tagger v0.1 I noticed the following
problems:

   1. is no separation between Divrey Hayamin A and B and nor for Shmuel A
   and B and nor for Melachim A and B.
   2. In book Dvarim Chapter 13 there are only 10 vertices instead of 18.

@omishali <https://github.com/omishali> @TechnionTDK/team-jbs-web-tagger
<https://github.com/orgs/TechnionTDK/teams/team-jbs-web-tagger>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TechnionTDK/jbs-web-tagger/issues/29>, or mute the
thread

**Comment by lchayoun** [comment]
issue is opened under TechnionTDK/jbs-text2json#27
